# ===============
# ACTION MARKDOWN
# ===============

name: Action-Markdown

# Activation Events
# =================

on:
  # When the action.yaml file changes
  push:
    paths:
      - action.yaml

  # Manual workflow dispatch
  workflow_dispatch:

# Jobs
# ====

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      # Checkout Repository âœ…
      # ======================

      - name: checkout
        uses: actions/checkout@v3

      # Generate Action Markdown Outputs ðŸ“œ
      # ===================================

      - name: generate action markdown
        id: action-md
        uses: Shresht7/action-markdown@main

      # Markdown Slots ðŸ“‹
      # =================

      - name: update readme slots
        id: markdown-slots
        uses: Shresht7/markdown-slots@main
        with:
          slots: |
            inputs: ${{ steps.action-md.outputs.inputs-md-table }}
            outputs: ${{ steps.action-md.outputs.outputs-md-table }}

      # Push Changes ðŸŒŽ
      # ===============
      - name: check for changes
        id: git-diff
        run: |
          if git diff --exit-code; then
            echo "::set-output name=changes_exist::false"
          else
            echo "::set-output name=changes_exist::true"
          fi

      - name: log shell
        run: echo ${{ steps.git-diff.outputs.changes_exist }}

      - name: git status
        run: git status

      - name: push
        if: ${{ steps.git-diff.outputs.changes_exist }}
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'Update README.md'
          git push
